title: Learn Basic Skills Git & GitHub
tags:
  - git
  - GitHub
  - Basic Skills
  - Beginners
  - Academy Learning Original
helpUrl: https://wix.slack.com/archives/C01CP5DARQT
helpText: 'Post on the #learning-git Slack channel'
description: >-
  Using git & GitHub is in the core of everything we do, 
steps:
  - link: 'https://github.com/about'
    title: What is GitHub?
    description: >-
      Hey, it's your first time here, so let's not take any chances. Check out
      this short video to understand why people use GitHub.
    video: 'https://youtube.com/embed/w3jLJU7DT5E'
      
  - title: Discover what can you do on GitHub
    link: https://docs.github.com/en/github/getting-started-with-github
    description: >-
      Learn how to start building, shipping, and maintaining software with GitHub. 
      Explore GitHub products and connect with the world's largest development community.
    video: 'https://youtube.com/embed/noZnOSpcjYY'
  
  - title: ðŸ“º Watch Git Explained in 100 Seconds (assuming you work with vscode ðŸ™ˆ)
    video: 'https://youtube.com/embed/hwP7WQkmECE'
    link: https://code.visualstudio.com/docs/editor/versioncontrol
    description: >-
      Learn the basics of Git in 100 seconds on vscode
  
  - course: githubtraining/introduction-to-github
    description: >-
      That video is pretty cool, right? If you want to learn how to use the
      workflow described in that video, take this course.

  
  - link: 'https://guides.github.com/introduction/git-handbook/'
    title: Git Handbook
    description: >-
      By now you are probably wondering what a Git is and why it is important in
      writing code. We have you covered with this short article on version
      control with Git.
      
  - course: githubtraining/communicating-using-markdown
    description: >-
      GitHub is all about collaboration and we collaborate in issues in pull
      requests. Learn how to get your point across with the worlds easiest text
      formatting syntax.

  - course: githubtraining/uploading-your-project-to-github
    description: >-
      Now that you know what GitHub does, I bet you're ready to move all of
      those projects off your local machine. This course will show you how.

  - title: ðŸ‘©â€âœˆï¸ Learn how to get out of messy situations, get familiar with troubleshooting & "flight rules" guides  
    link: https://github.com/k88hudson/git-flight-rules
    description: >-
      Getting into troubles with git can happen, learn how to get unstuck.
      Don't worry, even pros find Git confusing sometimes, and solve problems by searching for solutions on the web, 
      or consulting sites like Flight rules or https://dangitgit.com/

  - title: (Optional) Play "THE FLAME OF OPEN SOURCE" on TwilioQuest
    description: >-
      learn how to make your first contribution to an open source project, and clear the way for future developers using the power of the Flame of Open Source!
    video: 'https://youtube.com/embed/v6yyc40mYtI'
    link: 'https://www.twilio.com/quest/learn/open-source'
      
  - title: (Optional) git fundamentals by Adam Matan
    link: https://twitter.com/adam_matan/status/1149317853616775168
    video: 'https://youtube.com/embed/FlpXes7QVk4'
    description: >-
      Adama Matan explains the git fundamentals: file structure, SHAs and objects, commits, refs and branches, up to the git interactive rebase. 
      After this session, you should be able to understand git man pages, error messages, and repo states.
  - title: (Optional) Practice the Katas mentioned in Adam's talk
    link: https://github.com/adamatan/git
    description: >-
      Practice the Katas, preferrably with a partner - one of you reading the instructions, the other one typing commands, and vice versa. 
      Move to the next Kata only when you fully understand the commands you type and their effect.
  
  - title: (Optional) take Linkedin git skill Assessment quiz
    link: https://www.linkedin.com/skill-assessments/git/quiz/?practiceMode=true
    description: >-
      Take the quiz as a challenge, in the future it feel very easy don't worry ðŸ™ˆ
      15 multiple choice questions
      1.5 minutes per question
      Score in the top 30% to earn a badge
